"""role and slug add

Revision ID: b41aaed43620
Revises: dd1b3ac32c95
Create Date: 2022-04-24 20:24:15.552735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b41aaed43620'
down_revision = 'dd1b3ac32c95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complement_types', sa.Column('slug', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'complement_types', ['slug'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'complement_types', type_='unique')
    op.drop_column('complement_types', 'slug')
    # ### end Alembic commands ###
